language: python
matrix:
  include:
    - python: "3.8.3"
    - python: "nightly"
  allow_failures:
    - python: "nightly"

# command to install dependencies
install:
  - pip install python-dateutil pytest mock python-coveralls pytest-cov coverage
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.8.3" ]]; then
    pip install git+https://github.com/xbmc/addon-check.git;
    fi

# command to run tests
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.8.3" ]]; then
    kodi-addon-checker $TRAVIS_BUILD_DIR --branch=matrix;
    fi
  - py.test --cov coveralls --cov-report term-missing --cov=resources tests/

after_success:
  - coveralls
